### ISSUE TITLE
avcodec_open2 failed

### ISSUE THREAD

**Issue by lihongyi1234** [glumes/ffmpeg_android#1]
thank you for your project,its great that i learn l lot, I have a problem when run your project in my phone, have you counter this problem  
![微信图片_20211221181429](https://user-images.githubusercontent.com/36233282/146912728-44e9fc39-91a8-4f2b-b24c-5338c333db48.png)

**Comment by glumes** [comment]
确认一下编译的 ffmpeg 有没有带 mediacodec 吧

**Comment by lihongyi1234** [comment]
我确定一下你这边是跑通了是吧

**Comment by glumes** [comment]
是的，我的跑通了，另外除了编译问题，你确认一下 av_jni_set_java_vm 函数调用了没

**Comment by lihongyi1234** [comment]
没有调用这个函数，我加了之后没有报avcodec_open2 的错了，感谢

**Comment by glumes** [comment]
好咧，有问题也可以加我微信 ezglumes 及时讨论交流~~

**Comment by LxzBUG** [comment]
我调了 av_jni_set_java_vm avcodec_open2也失败了 用的ffmpeg 5.1

**Comment by LxzBUG** [comment]
Generic error in an external library
